name: Run CI
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  merge_group:
    types: [ checks_requested ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1
  SHELL: /bin/bash

jobs:

  ci-wasm:
    name: Wasm
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: 4.0.9
          actions-cache-folder: emsdk-cache
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install
        run: |
          rustup target add wasm32-unknown-emscripten
      - name: Build
        run: cargo build --target wasm32-unknown-emscripten